### ISSUE TITLE
It is difficult to distinguish colors on graphs produced by R script

### ISSUE THREAD

**Issue by ligurio** [tlaplus/Survey#1]
[R script](README.Rmd) produces graphs with many shades of each color. Due to this, it is difficult  to distinguish colors on graphs.

Example: 
![image](https://user-images.githubusercontent.com/1151557/168661764-26454e84-9b82-46fc-b1ee-a751baad7a8e.png)

(Discussed in https://twitter.com/estet/status/1526096153036705793)

**Comment by lemmy** [comment]
Without the legend, there is more screen estate for the plot which makes it easier to read the x-axis label: https://github.com/tlaplus/Survey/blob/a79239aec4de73cdd0e92b8b318be779ee10042f/README_files/figure-gfm/unnamed-chunk-1-1.png

**Comment by lemmy** [comment]
Please reopen if the removal of the legend didn't solve this.

**Comment by ligurio** [comment]
Looks much better. Thanks!
